#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-scikit_learn
Version  : 1.2.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/27/a0/95eae31ceabeb7710a694367816edfcc0ccb001c794c14b3b234c148ae50/scikit-learn-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/27/a0/95eae31ceabeb7710a694367816edfcc0ccb001c794c14b3b234c148ae50/scikit-learn-1.2.0.tar.gz
Summary  : A set of python modules for machine learning and data mining
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-scikit_learn-license = %{version}-%{release}
Requires: pypi-scikit_learn-python = %{version}-%{release}
Requires: pypi-scikit_learn-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cython)
BuildRequires : pypi(numpy)
BuildRequires : pypi(scipy)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
This directory contains bundled external dependencies that are updated
every once in a while.

%package license
Summary: license components for the pypi-scikit_learn package.
Group: Default

%description license
license components for the pypi-scikit_learn package.


%package python
Summary: python components for the pypi-scikit_learn package.
Group: Default
Requires: pypi-scikit_learn-python3 = %{version}-%{release}

%description python
python components for the pypi-scikit_learn package.


%package python3
Summary: python3 components for the pypi-scikit_learn package.
Group: Default
Requires: python3-core
Provides: pypi(scikit_learn)
Requires: pypi(joblib)
Requires: pypi(numpy)
Requires: pypi(scipy)
Requires: pypi(threadpoolctl)

%description python3
python3 components for the pypi-scikit_learn package.


%prep
%setup -q -n scikit-learn-1.2.0
cd %{_builddir}/scikit-learn-1.2.0
pushd ..
cp -a scikit-learn-1.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1686157448
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-scikit_learn
cp %{_builddir}/scikit-learn-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pypi-scikit_learn/d12e7b6f7e408c7ae7a878d4a207cfc7256e19b5 || :
cp %{_builddir}/scikit-learn-%{version}/sklearn/svm/src/liblinear/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-scikit_learn/98a0f7cd8d323be9a1aea7f957868b11361c4f51 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-scikit_learn/98a0f7cd8d323be9a1aea7f957868b11361c4f51
/usr/share/package-licenses/pypi-scikit_learn/d12e7b6f7e408c7ae7a878d4a207cfc7256e19b5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
